version: "3.7"
  
services:
  capesc10:
    image: capes/c10
    volumes:
      - c10_moodledata:/var/moodledata
      - c10_dbdata:/var/lib/postfresql/9.5/main
      - c10_logs:/var/log
    ports:
      - 8555:80

volumes:
  c10_moodledata:
  c10_dbdata:
  c10_logs:
